-- Baseline: the schema Hibernate's ddl-auto=update produced from the entity
-- classes before Flyway took over, taken from a pg_dump --schema-only of a
-- fresh Postgres 15 database. Constraint names are Hibernate's generated ones,
-- kept verbatim so databases created here and databases baselined from an
-- existing Hibernate-built schema end up identical, and later migrations can
-- refer to either by the same name.
--
-- Existing installs never run this file: spring.flyway.baseline-on-migrate
-- stamps a non-empty schema as version 1 instead.

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    password character varying(255),
    role character varying(255),
    username character varying(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE file_metadata (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone,
    current_version integer,
    filename character varying(255),
    is_directory boolean,
    last_accessed timestamp(6) without time zone,
    path character varying(255),
    size bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    CONSTRAINT file_metadata_pkey PRIMARY KEY (id),
    CONSTRAINT fkbmcm0tv2jdh9rad78gvhye174 FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE file_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone,
    size bigint,
    stored_filename character varying(255) NOT NULL,
    version integer NOT NULL,
    user_id bigint,
    file_id bigint NOT NULL,
    CONSTRAINT file_versions_pkey PRIMARY KEY (id),
    CONSTRAINT fkn12io8jqb37bmjcjktlt5kyjr FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fkoipk7el4suwg1l3kmcgo4dk19 FOREIGN KEY (file_id) REFERENCES file_metadata (id)
);

CREATE TABLE file_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    change_type character varying(255),
    error_message character varying(255),
    file_path character varying(255),
    filename character varying(255),
    success boolean NOT NULL,
    "timestamp" timestamp(6) without time zone,
    file_id bigint,
    user_id bigint,
    CONSTRAINT file_history_pkey PRIMARY KEY (id),
    CONSTRAINT file_history_change_type_check
        CHECK (change_type IN ('UPLOAD', 'DELETE', 'CREATE_FOLDER')),
    CONSTRAINT fkny1qisdo63yhqlibj91d8udfc FOREIGN KEY (file_id) REFERENCES file_metadata (id),
    CONSTRAINT fkex4t9e62f4wjet7sv3wc6vmva FOREIGN KEY (user_id) REFERENCES users (id)
);
