-- Share links, kept on the server. A link used to be a signed JWT naming a
-- path: anyone holding it could read the path, it could not be withdrawn
-- before it expired, and it served whatever was at that path when it was
-- opened, even a different file created later.
--
-- Now the URL carries only a random token, of which this table keeps just a
-- SHA-256 hash, and each link belongs to the file_metadata row it was made
-- for: deleting the file deletes its links. path is the item's path when the
-- link was made; a link whose row has since moved elsewhere stops working.
--
-- Links issued before this migration were never stored anywhere and stop
-- working; they expired within 7 days anyway.
CREATE TABLE share_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    token_hash character varying(64) NOT NULL,
    file_id bigint NOT NULL,
    path character varying(4096) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone,
    created_by bigint,
    CONSTRAINT share_links_pkey PRIMARY KEY (id),
    CONSTRAINT uk_share_links_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_share_links_file
        FOREIGN KEY (file_id) REFERENCES file_metadata (id) ON DELETE CASCADE,
    CONSTRAINT fk_share_links_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

-- Listing a file's links, and the cascade when its row is deleted.
CREATE INDEX idx_share_links_file ON share_links (file_id);
