-- Accounts of their own. Every account used to share one serving directory,
-- one file tree and one history. Now each account has a folder of its own
-- (.users/<id>/ in the serving directory), and its files, versions, history
-- and share links are its alone. Admins manage the other accounts.
--
-- Everything stored so far was stored in the one shared space, which becomes
-- the first account's: the app moves the files on disk into that account's
-- folder when it starts (see LooseFileAdoption), where their paths relative to
-- the folder are the paths the rows already hold, and this gives it the rows.

-- 1. users: whether the account can sign in, an optional cap on what it
--    stores, and a counter bumped to end its sessions (when it is disabled,
--    its role changes or its password is reset).
ALTER TABLE users
    ADD COLUMN enabled boolean NOT NULL DEFAULT true,
    ADD COLUMN quota_bytes bigint,
    ADD COLUMN session_version integer NOT NULL DEFAULT 0,
    ADD CONSTRAINT ck_users_quota_bytes CHECK (quota_bytes > 0);

-- The first account is the owner, who has to be able to manage the others.
-- Installs from before the setup code gave the owner ROLE_USER.
UPDATE users SET role = 'ROLE_ADMIN' WHERE id = (SELECT min(id) FROM users);
UPDATE users SET role = 'ROLE_USER'
WHERE role IS NULL OR role NOT IN ('ROLE_ADMIN', 'ROLE_USER');

ALTER TABLE users
    ALTER COLUMN role SET NOT NULL,
    ADD CONSTRAINT ck_users_role CHECK (role IN ('ROLE_ADMIN', 'ROLE_USER'));

-- 2. Every file and every history entry belongs to the first account, whoever
--    made it: they are all in its folder now.
UPDATE file_metadata SET user_id = (SELECT min(id) FROM users);
UPDATE file_history SET user_id = (SELECT min(id) FROM users);

-- Rows with no account to give them to (there is no account at all). Setup
-- gives the files on disk to the account it creates, where they show up
-- like files copied in by hand.
DELETE FROM file_metadata WHERE user_id IS NULL;

-- Paths are unique within an account's folder; two accounts can each have
-- a report.txt.
ALTER TABLE file_metadata
    ALTER COLUMN user_id SET NOT NULL,
    DROP CONSTRAINT uk_file_metadata_path,
    ADD CONSTRAINT uk_file_metadata_owner_path UNIQUE (user_id, path);

-- History is read one account at a time, newest first.
DROP INDEX idx_file_history_timestamp;
CREATE INDEX idx_file_history_user_timestamp ON file_history (user_id, "timestamp");

-- 3. One-time links an admin hands someone to choose a password with: an
--    invitation to create an account, or a reset of an account's password.
--    As with share links, only a SHA-256 hash of the token is kept, and using
--    a link deletes it.
CREATE TABLE account_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    token_hash character varying(64) NOT NULL,
    purpose character varying(32) NOT NULL,
    -- An invitation's account: its username, role and quota.
    username character varying(255),
    role character varying(255),
    quota_bytes bigint,
    -- A password reset's account.
    user_id bigint,
    created_by bigint,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT account_links_pkey PRIMARY KEY (id),
    CONSTRAINT uk_account_links_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_account_links_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_account_links_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_account_links_purpose CHECK (
        (purpose = 'INVITE' AND username IS NOT NULL AND role IN ('ROLE_ADMIN', 'ROLE_USER')
            AND user_id IS NULL)
        OR (purpose = 'PASSWORD_RESET' AND user_id IS NOT NULL AND username IS NULL)
    )
);

-- One open invitation per username and one open reset per account: making a
-- new one replaces the old, and two admins making one at once can't both
-- succeed.
CREATE UNIQUE INDEX uk_account_links_invite ON account_links (username)
    WHERE purpose = 'INVITE';
CREATE UNIQUE INDEX uk_account_links_reset ON account_links (user_id)
    WHERE purpose = 'PASSWORD_RESET';
